/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CCCC */

#ifndef _Included_CCCC
#define _Included_CCCC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CCCC
 * Method:    getAddress
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_CCCC_getAddress
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
